[customizations.installer.kickstart]
contents = """
%post --erroronfail --nochroot
bootc install-source docker://ghcr.io/jianzcar/zena-os:latest
bootc switch --transport registry docker://ghcr.io/jianzcar/zena-os:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
disable = [
]
