---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 11 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "${{ github.ref_name == 'main' && 'stable' || github.ref_name == 'testing' && 'testing' || 'stable' }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    outputs:
      tags: ${{ steps.set_tags.outputs.tags }}
      rechunk_ref: ${{ steps.rechunk.outputs.ref }}

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e
        with:
          remove-codeql: true

      - name: Get current date (UTC)
        id: date
        run: |
          echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "short_date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Set image tags
        id: set_tags
        run: |
          DATE=${{ steps.date.outputs.short_date }}
          TAGS="${DEFAULT_TAG} ${DEFAULT_TAG}.${DATE}"
          echo "TAGS=$TAGS" >> $GITHUB_ENV
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Prepare build args file
        env:
          DEFAULT_TAG: ${{ env.DEFAULT_TAG }}
        run: |
          cat <<EOF > build_args.txt
          DEFAULT_TAG=${DEFAULT_TAG}
          EOF

      - name: Build image (buildah)
        id: build_image
        run: |
          sudo buildah bud \
            --build-arg-file build_args.txt \
            --format docker \
            --tag "localhost/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}" \
            --file Containerfile

      - name: Run Rechunker
        id: rechunk
        uses: hhd-dev/rechunk@v1.2.3
        with:
          rechunk: 'ghcr.io/hhd-dev/rechunk:v1.2.3'
          ref: "localhost/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}"
          prev-ref: "${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DEFAULT_TAG }}"
          skip_compression: false
          version: ${{ steps.set_tags.outputs.tags }}

      - name: Set up skopeo
        uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest

      - name: Save rechunked image to docker-archive
        id: save_archive
        run: |
          RECHUNK_REF="${{ steps.rechunk.outputs.ref }}"
          echo "Rechunk ref: ${RECHUNK_REF}"
          sudo skopeo copy "${RECHUNK_REF}" "docker-archive:image.tar"

      - name: Upload image artifact
        uses: actions/upload-artifact@v5
        with:
          name: image-tar
          path: image.tar

      - name: Cleanup container storage
        run: |
          sudo podman system prune -a -f --volumes || true

  push:
    name: Push
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
          path: .

      - name: Set up skopeo
        uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest

      - name: Push image from archive via skopeo
        id: push_image
        env:
          TAGS: ${{ needs.build.outputs.tags }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
        run: |
          set -euo pipefail

          IMAGE_NAME_LC=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REGISTRY_LC=$(echo "${IMAGE_REGISTRY}" | tr '[:upper:]' '[:lower:]')
          echo "image_name=${IMAGE_NAME_LC}" >> $GITHUB_OUTPUT
          echo "image_registry=${IMAGE_REGISTRY_LC}" >> $GITHUB_OUTPUT

          for tag in $TAGS; do
            TARGET="docker://${IMAGE_REGISTRY_LC}/${IMAGE_NAME_LC}:${tag}"
            echo "Pushing ${TARGET} from docker-archive:image.tar"
            sudo skopeo copy --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
              "docker-archive:image.tar" \
              "$TARGET"
            echo "Published ${IMAGE_REGISTRY_LC}/${IMAGE_NAME_LC}:${tag}"
          done

      - name: Install Cosign (for signing)
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62

      - name: Login to GHCR for Cosign
        run: |
          cosign login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Sign images with Cosign
        env:
          TAGS: ${{ needs.build.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          IMAGE_NAME: ${{ steps.push_image.outputs.image_name }}
          IMAGE_REGISTRY: ${{ steps.push_image.outputs.image_registry }}
        run: |
          if [ -z "${COSIGN_PRIVATE_KEY}" ]; then
            echo "COSIGN_PRIVATE_KEY not set; skipping signing."
            exit 0
          fi

          for tag in $TAGS; do
            IMAGE_FULL="${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}"
            echo "Signing ${IMAGE_FULL}"
            cosign sign -y --key env://COSIGN_PRIVATE_KEY "${IMAGE_FULL}"
          done
